# Generated by Django 4.0.1 on 2022-12-26 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0.0, verbose_name='user_id')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='company_name')),
                ('field', models.CharField(blank=True, max_length=255, null=True, verbose_name='field')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_joined')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
