# Generated by Django 4.0.1 on 2022-12-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='position'),
        ),
    ]
