# Generated by Django 4.0.1 on 2023-01-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_work_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='award_received',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='award_received'),
        ),
    ]
