# Generated by Django 4.0.1 on 2022-11-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_barangay_user_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_attended',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='last_attended'),
        ),
        migrations.AddField(
            model_name='user',
            name='middlename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='middlename'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='student_number'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='work_status'),
        ),
    ]
