# Generated by Django 4.0.1 on 2023-01-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='no_people',
            field=models.IntegerField(default=0.0, verbose_name='no_people'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_announcement',
            field=models.IntegerField(default=0.0, verbose_name='notification_announcement'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_event',
            field=models.IntegerField(default=0.0, verbose_name='notification_event'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_job',
            field=models.IntegerField(default=0.0, verbose_name='notification_announcement'),
        ),
    ]
