# Generated by Django 4.0.1 on 2023-01-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_no_people_user_notification_announcement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='country_code'),
        ),
    ]
