# Generated by Django 4.1.2 on 2023-04-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_civil_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='religion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='religion'),
        ),
    ]
