# Generated by Django 4.1.2 on 2023-04-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='course'),
        ),
    ]
