# Generated by Django 4.1.2 on 2023-06-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_locked',
            field=models.BooleanField(default=True, verbose_name='is_locked'),
        ),
    ]
