# Generated by Django 4.0.1 on 2022-12-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='views',
            field=models.IntegerField(default=0.0, verbose_name='views'),
        ),
    ]
