# Generated by Django 4.0.1 on 2022-12-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_remove_announcement_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
    ]
