# Generated by Django 4.0.1 on 2023-01-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_announcement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
