# Generated by Django 4.1.2 on 2023-04-22 02:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0.0, verbose_name='no_people')),
                ('course', models.CharField(blank=True, max_length=255, null=True, verbose_name='course')),
                ('year_graduated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='year_graduated')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
