# Generated by Django 4.0.1 on 2023-01-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0002_jobposting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
