# Generated by Django 4.0.1 on 2023-01-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0003_alter_jobposting_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='department',
            field=models.TextField(blank=True, null=True, verbose_name='department'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='qualification',
            field=models.TextField(blank=True, null=True, verbose_name='qualification'),
        ),
    ]
