# Generated by Django 4.0.1 on 2023-01-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0004_jobposting_department_jobposting_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='position',
            field=models.TextField(blank=True, null=True, verbose_name='position'),
        ),
    ]
