# Generated by Django 4.0.1 on 2022-12-25 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='views',
        ),
    ]
