# Generated by Django 4.0 on 2023-07-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='announcement_views',
        ),
        migrations.RemoveField(
            model_name='report',
            name='event_views',
        ),
        migrations.RemoveField(
            model_name='report',
            name='posting_views',
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='category'),
        ),
    ]
