# Generated by Django 4.1.2 on 2023-04-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0.0, verbose_name='user_id')),
                ('skills', models.CharField(blank=True, max_length=255, null=True, verbose_name='skills')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
